import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Chaters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Chaters</h1>

      <p>Chat, chat, and more chat</p>
    </div>
  );
};

export default Home;
